require("plugin")
require("set")
require("remaps")

-- import plugin configs
require("plugins.brackets")
require("plugins.colorscheme")
require("plugins.comments")
require("plugins.dap")
require("plugins.focus")
require("plugins.git")
require("plugins.harpoon")
require("plugins.lsp")
require("plugins.mason")
require("plugins.oil")
require("plugins.snippet")
require("plugins.telescope")
require("plugins.tex")
require("plugins.treesitter")
require("plugins.formatter")
